### PR TITLE
Added swig executables for Win and Mac

### PR DESCRIPTION
**Pull request by abhimanyusirohi**
### Mac
The preferred way of installing on Mac is by using `brew`. If you simply want to install SWIG on your system (not compile) then first install brew: https://brew.sh/
Once brew is installed, use `brew install swig` to install SWIG

To compile SWIG on your system, see "Required Tools" section here: http://www.swig.org/svn.html
Download, build and install the required tools (mainly Autoconf, Automake and libpcre (not pcre2))
Autoconf: http://ftpmirror.gnu.org/autoconf
Automake: http://ftpmirror.gnu.org/automake
libpcre: http://www.pcre.org/

Download the package for above tools, unzip and run the following commands for each tool under its directory:
```
./configure
make
sudo make install
```

Now goto the SWIG directory and run the following commands:
```
./autogen.sh
./configure
make
sudo make install
```

If all goes fine then the swig executable will be built in the root directory.

### Windows
SWIG provides a prebuilt executable for Windows (swig win). It can be downloaded from: http://www.swig.org/download.html

@PerkinElmer/chemdraw-desktop-reviewers

### CODE REVIEW

**Review by zhanglin-wu — APPROVED** [review]

**Review by cp-njohn — APPROVED** [review]

**Comment by stevebaxter** [comment]
What branch did you build off? You probably want to build off a release, not from master?

**Comment by stevebaxter** [comment]
Also, I thought we were going to use brew and choco for this? I'd like to delete this repo again if possible?

**Review by stevebaxter — CHANGES_REQUESTED** [review]
I think we need to clarify what branch we're building, and whether this is the right thing to do at all.

**Comment by abhimanyusirohi** [comment]
@stevebaxter I branched it from 3.0.12 tag and built from there.
I tried brew but it displays an error message for the outdated XCode:
```
Error: Your Xcode (7.3.1) is too outdated.
Please update to Xcode 8.3.3 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by stevebaxter** [comment]
So you just need to update your version of Xcode? Keep Xcode 7.3.1 around (just rename it before updating).

**Comment by abhimanyusirohi** [comment]
I already have another version of XCode on my system (Applications/XCode 8/XCode.app). brew needs to be pointed to this version somehow.
We already have the executable built now. We can update the documentation to prefer "brew" instead of installing individual modules when updating the binary.

**Comment by stevebaxter** [comment]
I think you need to rename Xcode.app to Xcode7.3.1.app (or whatever version it is) and then install Xcode 8 in the default location (from the app store). Make sure the latest version is the "default" Xcode.app.

**Comment by abhimanyusirohi** [comment]
What's the decision here? Do we need a SWIG repository with executable or the devs will be responsible for SWIG configuration on their machine?

**Comment by zhanglin-wu** [comment]
This seems like an easy approach. I'm OK with this solution.

**Comment by stevebaxter** [comment]
Personally I think:

1. We should try and avoid committing tools to git unless we have to (though worse than committing tools is having a complex manual tool install process as we do on Windows for Chem3D and CDXL)
2. Using a  package manager and an install script that is maintained through git seems like a nice solution to me.

If we do commit the tools please think about:

1. Do we need the whole swig source repo or just the binary tools?
2. How will we maintain this going forwards and across projects? How will we handle new versions of swig and other updates?
3. What version of swig have you actually built - did you build off master or off a release tag? If you're going to manually build the binaries (rather than using a package manager) then you need to be clear on what you are building.

@lqin-pki - would appreciate your input on this as well.

**Comment by zhanglin-wu** [comment]
Yeah, we have the same problem for almost all the third party tools or libraries, I guess. What we need from a third party is just the installer, which contains either the executables or libraries (and header files), and resource files. We almost never need the source code.

I believe creating a script that can install all third parties is really the way to go. This can be the oppertunity for us to start doing that.

But, why are we including all the source code of alomost all the third parties into ChemDraw? Anyone get any reason for that? I guess maybe this is just a habit?

**Comment by abhimanyusirohi** [comment]
`Do we need the whole swig source repo or just the binary tools?`
I don't think we need the source code in a repo because we do not plan to make any changes to it. We just need to build an executable.

`How will we maintain this going forwards and across projects? How will we handle new versions of swig and other updates?`
Just like now, we can have executables for the latest released version.

`What version of swig have you actually built - did you build off master or off a release tag?` 
SWIG 3.0.12 from the Rel-3.0.12 tag

**Comment by zhanglin-wu** [comment]
Using the installer instead of the source code could also save the build time, right?

**Comment by zhanglin-wu** [comment]
I created a page here to collect these kind of problems:
https://confluence-ext.perkinelmer.com/display/PMO/ChemDraw+Source+File+Organization+Proposal

Hope we will have Jira tasks for them eventually.

And for this task, let's create the script for it.

**Comment by abhimanyusirohi** [comment]
I think we are overthinking it, how often are we going to update SWIG, once or max twice a year(the last SWIG release was 8 months back in Jan) and when we do, it won't take more than an hour.

**Comment by zhanglin-wu** [comment]
OK, discussed a little bit with the team. So, the trouble is:
For Mac:
1. Upgrade Xcode to 8.3
2. Install brew manually or in command line?

For Windows:
1. Install choco manually or in command line?

Using a script needs to take sometime. Not everyone have Xcode 8 right now. Jenkins environment is using Xcode 7 right now, though should be a simple work to upgrade.

**Comment by abhimanyusirohi** [comment]
Closing this as we have decided to use script to install the build tools.

**Pull request closed without merging**
