### PR TITLE
Added swig executables for Win and Mac

### PR DESCRIPTION
**Pull request by abhimanyusirohi**
We have decided to use the binaries (instead of scripts) because of problems with scripts on build system and using binaries would be much simpler.

## Compiling SWIG

The current version is 3.0.12 on both Mac and Win

### Mac

To compile SWIG on your system, see "Required Tools" section here: http://www.swig.org/svn.html
Download, build and install the required tools (mainly Autoconf, Automake and libpcre (not pcre2))
Autoconf: http://ftpmirror.gnu.org/autoconf
Automake: http://ftpmirror.gnu.org/automake
libpcre: http://www.pcre.org/

Download the package for above tools, unzip and run the following commands for each tool under its directory:
```
./configure
make
sudo make install
```

Now goto the SWIG directory and run the following commands:
```
./autogen.sh
./configure
make
sudo make install
```

If all goes fine then the swig executable will be built in the root directory.

### Windows
SWIG provides a prebuilt executable for Windows (swig win). It can be downloaded from: http://www.swig.org/download.html

@PerkinElmer/chemdraw-desktop-reviewers

### CODE REVIEW

**Comment by abhimanyusirohi** [comment]
The `swig` folder needs to be referenced in `CommonThirdParty`

**Comment by stevebaxter** [comment]
I don't think you want to merge into master - instead you need to create a branch in swig off the release tag for the version you're wanting to use. You should commit your binaries there.

This will allow us to have different binaries on different branches so we can support different versions of SWIG across different products.

**Comment by stevebaxter** [comment]
I would use our release/ syntax, so SWIG 3.0.12 would use a branch called release/swig-3.0.12

**Comment by stevebaxter** [comment]
You may also want to add a readme.md in the bin folder (it should really be bin, not binaries) that explains how to build the binaries on both platforms. That way we capture the knowledge.

**Review by stevebaxter — CHANGES_REQUESTED** [review]
As described in the comments

**Comment by abhimanyusirohi** [comment]
`bin` seems to be always ignored by Git - I tried setting it to show modified files inside `bin` in gitignore but it won't show so I renamed it to binaries.

**Comment by stevebaxter** [comment]
Have you checked your global .gitignore? AFAIK nothing is "automatically" ignored.

**Comment by abhimanyusirohi** [comment]
Closing this PR as the work has been done in another PR. There is now a `release/3.0.12` branch under `swig` repository with a `bin` folder containing Win and Mac executable v3.0.12

**Pull request closed without merging**
